import Container from '@/components/shared/Container/Container';
import Section from '@/components/shared/Section/Section';
import Image from 'next/image';

export default function Sec3() {
  return (
    <Section>
      <Container className="text-center">
        <p className="text-lg mb-6">
          More than <span className="font-bold">25,000,000</span> images generated by creative
          companies globally
        </p>

        <div className="flex flex-wrap justify-center items-center gap-6 brand-strip">
          {[
            '/assets/NotLoggedHome/sec3/eleman-beauty.png',
            '/assets/NotLoggedHome/sec3/enzo-chehab.png',
            '/assets/NotLoggedHome/sec3/eva-candles.png',
            '/assets/NotLoggedHome/sec3/homes-of.png',
            '/assets/NotLoggedHome/sec3/the-shoeco.png',
          ].map((src, i) => (
            <a key={i} href="" className="m-4 flex items-center">
              <Image
                src={src}
                alt={`brand ${i}`}
                width={160}
                height={48}
                className="h-8 sm:h-12 w-auto"
              />
            </a>
          ))}
        </div>
      </Container>
    </Section>
  );
}
