'use client';
import Sec1 from '@/components/Home/NotLoggedHome/Sec1/Sec1';
import Sec10 from '@/components/Home/NotLoggedHome/Sec10/Sec10';
import Sec2 from '@/components/Home/NotLoggedHome/Sec2/Sec2';
import Sec3 from '@/components/Home/NotLoggedHome/Sec3/Sec3';
import Sec4 from '@/components/Home/NotLoggedHome/Sec4/Sec4';
import Sec5 from '@/components/Home/NotLoggedHome/Sec5/Sec5';
import Sec6 from '@/components/Home/NotLoggedHome/Sec6/Sec6';
import Sec7 from '@/components/Home/NotLoggedHome/Sec7/Sec7';
import Sec8 from '@/components/Home/NotLoggedHome/Sec8/Sec8';
import Sec9 from '@/components/Home/NotLoggedHome/Sec9/Sec9';
import UploadProductModal from '@/components/Home/uploadProductModal';
import Container from '@/components/shared/Container/Container';
import Loader from '@/components/shared/Loader/Loader';
import Section from '@/components/shared/Section/Section';
import { useAuthStore } from '@/store/authStore';
import { ArrowDown } from 'lucide-react';
import Image from 'next/image';
import { useState } from 'react';

export default function HomeFullPage() {
  const [isUploadOpen, setIsUploadOpen] = useState(false);
  const isAuth = useAuthStore((s) => s.isAuthenticated);
  const loading = useAuthStore((s) => s.loading);

  const sampleImages = [
    '/assets/Home/product1.jpg',
    '/assets/Home/product2.jpg',
    '/assets/Home/product3.jpg',
  ];

  if (loading) {
    return <Loader />;
  }

  return (
    <>
      {isAuth ? (
        <div className="relative w-full bg-background text-foreground">
          {isUploadOpen && <UploadProductModal onClose={() => setIsUploadOpen(false)} />}

          <Section className="pt-10 pb-16 sm:pt-16 sm:pb-20">
            <Container className="flex flex-col gap-10 sm:gap-12">
              {/* Header row */}
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Home</h1>

                <div className="flex w-full gap-3 sm:w-auto sm:justify-end">
                  <button
                    className="flex-1 rounded-lg border border-border bg-secondary px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-secondary-hover sm:flex-none sm:px-5
                      dark:border-border-dark dark:bg-secondary-dark dark:hover:bg-secondary-dark-hover"
                  >
                    Bulk generate
                  </button>

                  <button
                    className="flex-1 rounded-lg bg-main px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-main-hover sm:flex-none sm:px-5
                      dark:bg-main-dark dark:hover:bg-main-dark-hover"
                    type="button"
                    onClick={() => setIsUploadOpen(true)}
                  >
                    Upload new products
                  </button>
                </div>
              </div>

              {/* Content */}
              <div className="flex flex-col gap-12">
                {/* Get inspired */}
                <section className="flex flex-col gap-5">
                  <div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between">
                    <div>
                      <h2 className="text-xl font-semibold sm:text-2xl">Get inspired</h2>
                      <p className="mt-1 text-sm text-muted-foreground dark:text-muted-foreground-dark">
                        Check out these photos generated by Pebblely and create your own.
                      </p>
                    </div>

                    <button className="mt-2 text-sm font-medium underline-offset-2 hover:underline sm:mt-0">
                      View more
                    </button>
                  </div>

                  <div className="grid gap-2 sm:gap-6 grid-cols-1 sm:grid-cols-3 lg:grid-cols-3">
                    {sampleImages.map((src, index) => (
                      <div
                        key={index}
                        className="group relative aspect-[4/5] overflow-hidden rounded-lg bg-muted dark:bg-muted-dark"
                      >
                        <Image
                          src={src}
                          alt="Inspiration image"
                          fill
                          className="object-cover transition duration-200 group-hover:brightness-75"
                          sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
                        />

                        <div className="pointer-events-none absolute inset-0 flex items-end justify-end p-3 opacity-0 transition-opacity duration-200 group-hover:opacity-100 sm:p-4">
                          <button
                            className="pointer-events-auto rounded-lg bg-main px-3 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-main-hover sm:px-4 sm:text-sm
                              dark:bg-main-dark dark:hover:bg-main-dark-hover"
                          >
                            Generate
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </section>

                {/* Your assets */}
                <section className="flex flex-col gap-5">
                  <div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between">
                    <div>
                      <h2 className="text-xl font-semibold sm:text-2xl">Your assets</h2>
                      <p className="mt-1 text-sm text-muted-foreground dark:text-muted-foreground-dark">
                        Click on a product to get started or{' '}
                        <button className="ml-1 text-sm font-medium underline underline-offset-2">
                          upload
                        </button>
                        <span className="ml-1">a new product photo</span>
                      </p>
                    </div>
                    <button className="mt-2 text-sm font-medium underline-offset-2 hover:underline sm:mt-0">
                      View all
                    </button>
                  </div>

                  <div className="grid gap-2 sm:gap-6 grid-cols-1 sm:grid-cols-3 lg:grid-cols-6">
                    {sampleImages.map((src, index) => (
                      <div
                        key={index}
                        className="group relative aspect-[4/5] overflow-hidden rounded-lg bg-muted dark:bg-muted-dark"
                      >
                        <Image
                          src={src}
                          alt="Asset image"
                          fill
                          className="object-cover transition duration-200 group-hover:brightness-75"
                          sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 16vw"
                        />

                        <div className="pointer-events-none absolute inset-0 flex flex-col justify-between p-3 opacity-0 transition-opacity duration-200 group-hover:opacity-100 sm:p-4">
                          <div className="flex items-start justify-between text-sm sm:text-base text-white">
                            <span>Your product</span>
                            <div className="flex gap-1">
                              <button
                                aria-label="download"
                                className="pointer-events-auto rounded bg-white text-black px-2 py-1 text-xl w-8 h-8 flex items-center justify-center hover:bg-gray-200"
                              >
                                <ArrowDown size={16} />
                              </button>
                            </div>
                          </div>
                          <div className="flex justify-end">
                            <button
                              className="pointer-events-auto rounded-lg bg-main px-3 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-main-hover sm:px-4 sm:text-sm
                                dark:bg-main-dark dark:hover:bg-main-dark-hover"
                            >
                              Generate
                            </button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </section>

                {/* Recent */}
                <section className="flex flex-col gap-3">
                  <h2 className="text-xl font-semibold sm:text-2xl">Recent</h2>
                  <p className="text-sm text-muted-foreground dark:text-muted-foreground-dark">
                    No recent images
                  </p>
                </section>
              </div>
            </Container>
          </Section>
        </div>
      ) : (
        <div className="flex flex-col gap-32">
          <div>
            <Sec1 />
            <Sec2 />
          </div>
          <Sec3 />
          <div>
            <Sec4 />
            <Sec5 />
          </div>
          <Sec6 />
          <Sec7 />
          <Sec8 />
          <Sec9 />
          <Sec10 />
        </div>
      )}
    </>
  );
}
